// 夏鹏个人网站：可编辑内容与素材映射。
window.PORTFOLIO={name:'夏鹏',works:[
{label:'AI 无限',title:'用 AI 改善工作，把想法落地。',kind:'13 周成长计划',text:'六位老师授课，三个月陪跑。从可复用的工作流程，到能展示的个人作品，再到能试用的产品方案，在实践中走向自己的成果。夏鹏负责看清方向，张卓、刘学政、夏子钦、李新博与李萌萌分别陪伴成果表达、优势探索、视觉创作、项目落地与产品交付。',role:'工作效率 · 作品 · 产品',client:'6 位老师授课 · 三个月陪跑',period:'13 周',image:'/xiapeng/assets/ai-infinite.png',note:'海报所列限时价格为 3280 元，原价 7980 元。当前价格、开课时间与服务安排请向课程顾问确认。'},
{label:'涌现训练营',title:'让 AI 成为工作的日常。',kind:'职场 AI 涌现训练营',text:'从三天启动，到一年的持续训练。课程包含一年 AI 涌现社群、12 场每月直播、三天启动线上课、班主任课程服务、课程笔记与资料包，以及《个人工作方法 12 讲》视频课。用持续实践，积累可以复用的工作方法。',role:'AI 实践 · 职场成长',client:'社群、直播、课程与资料',period:'12 个月',image:'/xiapeng/assets/ai-emergence.jpg',note:'完整课程内容、服务期限及说明见下方原始海报。'},
{label:'友邻优课',title:'以英语为桥梁，读懂更广阔的世界。',kind:'英语与人文教育',text:'2015 年创立友邻优课，倡导深度英文阅读与终身学习。所提供资料记载，友邻优课拥有 600 万+ 用户，外刊课程成为南京大学线上课程，并曾获得喜马拉雅 123 知识节冠军。',role:'成人英语 · 人文阅读',client:'友邻优课 APP',period:'2015 年创立',image:'/xiapeng/assets/youlin-app.jpg',note:'扫描二维码下载 APP。课程咨询：我的 → 我的服务 → 班主任。'},
{label:'星途天下',title:'从认知，到行动，再到成果。',kind:'职场成长与 AI',text:'2023 年创办星途天下，聚焦职场成长与 AI 内容。从看清方向、发现优势，到用 AI 改善工作与推进项目，让学习落到具体行动里。所提供资料记载，创办一年内全网粉丝突破 500 万，累计粉丝超 1000 万。',role:'职业发展 · AI 实践',client:'内容、课程与持续陪伴',period:'2023 年创立',image:'/xiapeng/assets/portrait.jpg',note:'通过抖音关注夏鹏：xiapeng88888888。'},
{label:'冠军与履历',title:'持续学习，也陪伴他人成长。',kind:'表达 · 教育 · 创业',text:'2005 年，南京大学英语系大二学生夏鹏获得 IPSC 世界英语演讲比赛冠军，成为中国历史上第二位获此殊荣的选手，并获菲利普亲王接见授奖。此后曾任中国英语演讲国家队教练、新东方集团战略规划部总监与伦敦商学院客座讲师。',role:'世界英语演讲冠军',client:'友邻优课、星途天下创始人',period:'2005 年至今',image:'/xiapeng/assets/hero.jpg',note:'南京大学英语系本科；南京大学—约翰斯·霍普金斯大学中美文化研究中心深造；长江商学院优秀校友、哈佛商学院校友。所提供的 2026 年 9 月资料记载，斯坦福商学院高管项目在读。'}]};
(()=>{
const setText=(el,t)=>{if(el&&el.textContent.trim()!==t)el.textContent=t;};
let active=0;
function modal(title,body,src){let d=document.getElementById('profile-dialog');if(!d){d=document.createElement('dialog');d.id='profile-dialog';d.className='profile-dialog';document.body.append(d);d.addEventListener('click',e=>{if(e.target===d)d.close();});}d.replaceChildren();const close=document.createElement('button');close.className='profile-close';close.textContent='×';close.setAttribute('aria-label','关闭');close.onclick=()=>d.close();const h=document.createElement('h2');h.textContent=title;const p=document.createElement('p');p.textContent=body;d.append(close,h,p);if(src){const im=document.createElement('img');im.src=src;im.alt=title;d.append(im);}d.showModal();d.scrollTop=0;}
function showWork(i){const w=PORTFOLIO.works[i];modal(w.label,w.text+' '+w.note,w.image);}
function image(el,src,alt){if(el.getAttribute('src')!==src){el.src=src;el.removeAttribute('srcset');}el.alt=alt;}
function refresh(){
document.querySelectorAll('ht-service-badges span,ht-badge span span').forEach(e=>{const words={'Consulting':'英语表达','AI strategy':'AI 方向','Interim CTO':'演讲训练','Interim CPO':'终身学习','Process design':'深度阅读','Public sector':'人文教育','Website':'友邻优课','Web app':'英语学习','Smartphone app':'人文阅读','Automation':'内容创业','AI integration':'AI 实践','Fullstack':'职业成长','Accessibility':'成果表达','Operations & maintenance':'持续陪伴','Design system':'个人作品','Graphics':'视觉创作','Motion':'项目落地','Photo':'优势探索','Video':'产品交付'};const word=Object.keys(words).find(w=>w.toLowerCase()===e.textContent.trim().toLowerCase());if(word)setText(e,words[word]);});
const skillLabels={'Angular':'英语演讲','CI/CD':'终身学习','Docker':'人文阅读','Git':'教育创业','NestJS':'成果表达','Node.js':'内容创作','PHP':'项目实践','RxJS':'认知成长','Sass':'优势探索','SQL':'工作流程','Tailwind':'AI 应用','TypeScript':'行动方法','WordPress':'持续陪伴'};document.querySelectorAll('span').forEach(e=>{const k=e.textContent.trim();if(skillLabels[k]&&e.querySelector('i.icon'))setText(e,skillLabels[k]);});
document.documentElement.lang='zh-CN';document.title='夏鹏｜英语、职场与 AI · 持续成长';
const tabs=[...document.querySelectorAll('#selectedWorksSection [role="tab"]')];tabs.forEach((t,i)=>setText([...t.querySelectorAll('span')].find(s=>s.textContent.trim())||t,PORTFOLIO.works[i%5].label));const ai=tabs.findIndex(t=>t.getAttribute('aria-selected')==='true');active=Math.max(0,ai)%5;
const panel=document.getElementById('selected-works-panel');if(panel){const w=PORTFOLIO.works[active];panel.setAttribute('aria-label',w.title);setText(panel.querySelector('h3'),w.title);panel.querySelectorAll('ht-selected-works-detail p').forEach((p,i)=>setText(p,i===0?w.text:w.note));panel.querySelectorAll('dd').forEach(d=>setText(d,({'方向':w.role,'内容':w.client,'周期':w.period,Role:w.role,Client:w.client,Period:w.period})[d.previousElementSibling?.textContent.trim()]||w.kind));panel.querySelectorAll('ht-badge span span').forEach((e,i)=>setText(e,i===0?w.kind:'学习与成长'));panel.querySelectorAll('img').forEach(im=>image(im,w.image,w.label));panel.querySelectorAll('ht-button-light a,ht-button-light button').forEach(b=>setText(b.querySelector('span:last-child')||b,'查看详情'));}
document.querySelectorAll('video').forEach(v=>{if(!v.dataset.profilePoster){v.dataset.profilePoster='1';if(v.closest('ht-hero'))v.parentElement.classList.add('profile-cover-frame');v.pause();v.removeAttribute('autoplay');v.removeAttribute('onloadstart');v.removeAttribute('oncanplay');v.removeAttribute('src');v.querySelectorAll('source').forEach(s=>s.remove());v.poster=v.closest('#selectedWorksSection')?PORTFOLIO.works[active].image:v.closest('#bentoSection')?'/xiapeng/assets/cgtn.jpg':'/xiapeng/assets/hero.jpg';v.load();}});
const pics={'beirat':'hero.jpg','d64':'youlin-app.jpg','tech-tonic':'portrait.jpg','fingerprint':'cctv.jpg','koalition':'collaboration.jpg'};document.querySelectorAll('#bentoSection img').forEach(im=>{for(const [a,b] of Object.entries(pics))if(im.src.includes(a))image(im,'/xiapeng/assets/'+b,'夏鹏 · 学习与交流');});
document.querySelectorAll('a').forEach(a=>{const href=a.getAttribute('href')||'';if(/linkedin|d-64.social|bsky.app|threads.net|instagram/.test(href)){a.dataset.profileAction='douyin';a.href='#douyin';a.removeAttribute('target');if(/linkedin/.test(href)){setText(a,'抖音');a.setAttribute('aria-label','关注夏鹏抖音');}else a.hidden=true;}else if(/threema/.test(href)){a.dataset.profileAction='app';a.href='#app';setText(a,'下载友邻优课 APP');}else if(/henning|d-64\.org|techundtonic|tilli\.me|mailto:/.test(href)){a.dataset.profileAction='local';a.href='#details';a.removeAttribute('target');}});
document.querySelectorAll('ht-blog article').forEach((a,i)=>{const data=[['CGTN 夏鹏访谈','cgtn.jpg'],['央视英文频道连线','cctv.jpg'],['国际合作合影','collaboration.jpg']][i%3];setText(a.querySelector('h3 a'),data[0]);const im=a.querySelector('img');if(im)image(im,'/xiapeng/assets/'+data[1],data[0]);a.lang='zh-CN';const time=a.querySelector('time');if(time)time.hidden=true;});
document.querySelectorAll('ht-selected-works-detail a').forEach(a=>{setText(a.querySelector('span:last-child')||a,'查看详情');a.setAttribute('aria-label','查看课程详情');});
document.querySelectorAll('video[data-profile-poster]').forEach(v=>v.setAttribute('aria-hidden','true'));
document.querySelectorAll('img[src="/xiapeng/images/ht-logo.svg"]').forEach(im=>im.alt='夏鹏标志');
document.querySelectorAll('img[src="/xiapeng/images/profile.jpg"]').forEach(im=>{im.alt='夏鹏个人肖像';im.parentElement.parentElement.classList.add('profile-portrait-frame');});
}
document.addEventListener('click',e=>{const t=e.target.closest('a,button,[data-cal-link]');if(!t)return;const label=(t.textContent.trim()||t.getAttribute('aria-label')||''),href=t.getAttribute('href')||'';const work=t.closest('#selected-works-panel');if(work&&!t.matches('[role=tab]')&&!t.closest('[role=tab]')){e.preventDefault();e.stopImmediatePropagation();showWork(active);return;}
let action=null;if(t.dataset.profileAction==='douyin'||label==='关注夏鹏')action=()=>modal('关注夏鹏','抖音号：xiapeng88888888。曾经被照亮，也想成为光。','/xiapeng/assets/douyin.jpg');else if(t.dataset.profileAction==='app'||/下载友邻优课/.test(label))action=()=>showWork(2);else if(/查看 AI 无限|查看成长课程|查看 AI 课程/.test(label)||t.closest('[data-cal-link]'))action=()=>showWork(0);else if(/查看训练营/.test(label))action=()=>showWork(1);else if(/查看教育经历|查看个人履历|了解冠军经历/.test(label))action=()=>showWork(4);else if(/了解星途天下|了解创业历程/.test(label))action=()=>showWork(3);else if(/查看访谈照片|^查看照片$/.test(label))action=()=>modal('CGTN 夏鹏访谈','媒体访谈照片，来自你提供的人物资料。','/xiapeng/assets/cgtn.jpg');else if(/查看合作照片/.test(label))action=()=>modal('国际合作与人文交流','与世界连接，在交流中持续学习。','/xiapeng/assets/collaboration.jpg');else if(/impressum|datenschutz/.test(href))action=()=>modal(label,'本页依据所提供的夏鹏个人介绍、课程海报与照片整理。资料截至 2026 年 9 月；课程价格、安排与服务以实际咨询为准。本站不收集表单或支付信息。');else if(/中文|Deutsch|English/.test(label))action=()=>modal('语言','当前提供简体中文版。');else if(label==='查看全部照片')action=()=>{modal('照片与现场','媒体访谈、央视连线与国际合作。','/xiapeng/assets/cgtn.jpg');for(const src of ['/xiapeng/assets/cctv.jpg','/xiapeng/assets/collaboration.jpg']){const im=document.createElement('img');im.src=src;im.alt='夏鹏 · 交流现场';document.getElementById('profile-dialog').append(im);}};else if(t.dataset.profileAction==='local'){action=()=>{if(/CGTN/.test(label))modal('CGTN 夏鹏访谈','媒体访谈现场。','/xiapeng/assets/cgtn.jpg');else if(/央视/.test(label))modal('央视英文频道连线','媒体交流现场。','/xiapeng/assets/cctv.jpg');else if(/国际合作/.test(label))modal('国际合作合影','国际交流现场。','/xiapeng/assets/collaboration.jpg');else showWork(0);};}if(action){e.preventDefault();e.stopImmediatePropagation();action();}},true);
let queued=false;function schedule(){if(!queued){queued=true;requestAnimationFrame(()=>{queued=false;refresh();});}}document.addEventListener('DOMContentLoaded',()=>{new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();});
})();
